name: Release

on:
  release:
    types: [published]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Release published
        run: echo "Release ${{ github.event.release.tag_name }} published"
